/**
 * Onboarding Routine Library
 * 
 * Normalized routine library with tags for multiple discovery paths.
 * Each routine can belong to multiple personas and have multiple objectives.
 * 
 * Naming convention for IDs: kebab-case, descriptive (e.g., 'commandes-sans-ar')
 * 
 * IMPORTANT: Routines with identical labels across personas share the same ID
 * (e.g., "Suivi des priorités" appears for multiple personas but has one ID)
 */

import type {
  RoutineLibraryEntry,
  PersonaDefaultSets,
  Persona,
} from './types';

export const ROUTINE_LIBRARY: RoutineLibraryEntry[] = [
  // === APPROVISIONNEUR ===
  {
    id: 'commandes-sans-ar',
    label: 'Commandes sans AR',
    description: 'Suivre les commandes en attente d\'accusé de réception',
    personas: ['Approvisionneur'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['AR', 'acknowledgement', 'accusé', 'réception'],
  },
  {
    id: 'commandes-en-retard',
    label: 'Commandes en retard',
    description: 'Identifier et gérer les commandes fournisseurs en retard',
    personas: ['Approvisionneur'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['retard', 'delay', 'fournisseur', 'supplier'],
  },
  {
    id: 'impact-des-retards',
    label: 'Impact des retards',
    description: 'Analyser l\'impact des retards fournisseurs sur la production',
    personas: ['Approvisionneur'],
    objectives: ['Anticiper', 'Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier', 'Production'],
    frequency: 'Daily',
    pelicoViews: ['Supply', 'Event Explorer'],
    keywords: ['impact', 'retard', 'production'],
  },
  {
    id: 'actions-fournisseurs',
    label: 'Actions fournisseurs',
    description: 'Suivre les actions en cours avec les fournisseurs',
    personas: ['Approvisionneur'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['action', 'fournisseur', 'supplier'],
  },
  {
    id: 'relances-fournisseurs',
    label: 'Relances fournisseurs',
    description: 'Gérer les relances nécessaires auprès des fournisseurs',
    personas: ['Approvisionneur'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['relance', 'follow-up'],
  },
  {
    id: 'solde-a-moins',
    label: 'Solde à moins',
    description: 'Suivre les soldes négatifs et les besoins urgents',
    personas: ['Approvisionneur'],
    objectives: ['Anticiper'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['solde', 'négatif', 'stock'],
  },
  {
    id: 'reporting-management',
    label: 'Reporting management',
    description: 'Générer les rapports de suivi pour le management',
    personas: ['Approvisionneur'],
    objectives: ['Reporter'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Escalation Room'],
    keywords: ['reporting', 'management', 'rapport'],
  },
  {
    id: 'planning-fournisseur',
    label: 'Planning fournisseur',
    description: 'Suivre le planning de livraison des fournisseurs',
    personas: ['Approvisionneur'],
    objectives: ['Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['planning', 'fournisseur', 'livraison'],
  },
  {
    id: 'impact-fournisseur',
    label: 'Impact fournisseur',
    description: 'Analyser l\'impact global des fournisseurs',
    personas: ['Approvisionneur'],
    objectives: ['Piloter', 'Reporter'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Weekly',
    pelicoViews: ['Supply'],
    keywords: ['impact', 'fournisseur'],
  },
  {
    id: 'collaboration-fournisseur',
    label: 'Collaboration fournisseur',
    description: 'Faciliter la collaboration avec les fournisseurs',
    personas: ['Approvisionneur'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['collaboration', 'fournisseur'],
  },
  {
    id: 'risques-rupture-fournisseur',
    label: 'Risques de rupture fournisseur',
    description: 'Anticiper les risques de rupture chez les fournisseurs',
    personas: ['Approvisionneur'],
    objectives: ['Anticiper'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['risque', 'rupture', 'fournisseur'],
  },
  {
    id: 'of-lancables',
    label: 'OF lançables',
    description: 'Identifier les ordres de fabrication prêts à être lancés',
    personas: ['Approvisionneur'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'ordre', 'fabrication', 'lancable'],
  },
  {
    id: 'of-sous-traitance-non-servis',
    label: 'OF sous-traitance non servis',
    description: 'Suivre les OF en sous-traitance non servis',
    personas: ['Approvisionneur'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'sous-traitance', 'subcontract'],
  },
  {
    id: 'priorisation-tickets',
    label: 'Priorisation des tickets',
    description: 'Prioriser les tickets selon leur urgence et impact',
    personas: ['Approvisionneur'],
    objectives: ['Arbitrer'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['priorisation', 'ticket', 'priorité'],
  },
  {
    id: 'suivi-priorites',
    label: 'Suivi des priorités',
    description: 'Suivre l\'évolution des priorités et leur traitement',
    personas: [
      'Approvisionneur',
      'Acheteur',
      'Manager Appro',
      'Ordonnanceur Assemblage',
      'Ordonnanceur',
      'Master Planner',
      'Support Logistique',
      'Recette',
      'Responsable Supply Chain',
      'Directeur Supply Chain',
    ],
    objectives: ['Piloter', 'Arbitrer'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer', 'Business'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['priorité', 'suivi', 'priorities'],
  },
  {
    id: 'actions-en-cours',
    label: 'Actions en cours',
    description: 'Suivre l\'avancement des actions en cours',
    personas: [
      'Approvisionneur',
      'Acheteur',
      'Manager Appro',
      'Ordonnanceur Assemblage',
      'Ordonnanceur',
      'Master Planner',
      'Support Logistique',
      'Recette',
      'Responsable Supply Chain',
    ],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['action', 'en cours', 'suivi'],
  },
  {
    id: 'nettoyage-tickets',
    label: 'Nettoyage des tickets',
    description: 'Nettoyer et clôturer les tickets obsolètes',
    personas: [
      'Approvisionneur',
      'Acheteur',
      'Manager Appro',
      'Ordonnanceur Assemblage',
      'Ordonnanceur',
      'Master Planner',
      'Support Logistique',
      'Recette',
      'Responsable Supply Chain',
      'Directeur Supply Chain',
    ],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer'],
    frequency: 'Weekly',
    pelicoViews: ['Escalation Room'],
    keywords: ['nettoyage', 'ticket', 'clôture'],
  },

  // === ACHETEUR ===
  {
    id: 'suivi-evolution-actions-priorite',
    label: 'Suivi de l\'évolution des actions par priorité',
    description: 'Suivre l\'évolution des actions classées par priorité',
    personas: ['Acheteur'],
    objectives: ['Piloter', 'Arbitrer'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['évolution', 'action', 'priorité'],
  },

  // === MANAGER APPRO ===
  {
    id: 'top-fournisseurs-impact-business',
    label: 'Top fournisseurs à impact business',
    description: 'Identifier les fournisseurs ayant le plus d\'impact business',
    personas: ['Manager Appro', 'Directeur Supply Chain'],
    objectives: ['Reporter', 'Arbitrer'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering'],
    keywords: ['top', 'fournisseur', 'impact', 'business'],
  },
  {
    id: 'top-fournisseurs-retard',
    label: 'Top fournisseurs en retard',
    description: 'Identifier les fournisseurs avec le plus de retards',
    personas: ['Manager Appro', 'Directeur Supply Chain'],
    objectives: ['Corriger', 'Reporter'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering'],
    keywords: ['top', 'fournisseur', 'retard'],
  },
  {
    id: 'top-fournisseurs-sans-ar',
    label: 'Top fournisseurs sans AR',
    description: 'Identifier les fournisseurs avec le plus de commandes sans AR',
    personas: ['Manager Appro', 'Directeur Supply Chain'],
    objectives: ['Piloter', 'Reporter'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering'],
    keywords: ['top', 'fournisseur', 'AR', 'acknowledgement'],
  },
  {
    id: 'repartition-actions-equipes',
    label: 'Répartition des actions équipes',
    description: 'Visualiser la répartition des actions entre les équipes',
    personas: ['Manager Appro', 'Directeur Supply Chain'],
    objectives: ['Reporter', 'Arbitrer'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Escalation Room'],
    keywords: ['répartition', 'action', 'équipe'],
  },
  {
    id: 'suivi-kpis-pilotage',
    label: 'Suivi des KPIs de pilotage',
    description: 'Suivre les indicateurs clés de performance',
    personas: ['Manager Appro', 'Master Planner', 'Responsable Supply Chain', 'Directeur Supply Chain'],
    objectives: ['Reporter', 'Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering', 'Production Control', 'Customer Support'],
    keywords: ['KPI', 'indicateur', 'pilotage'],
  },

  // === ORDONNANCEUR ASSEMBLAGE ===
  {
    id: 'preparation-montage-j1',
    label: 'Préparation mise au montage J+1',
    description: 'Préparer la mise au montage pour le lendemain',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur'],
    objectives: ['Anticiper', 'Piloter'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['montage', 'préparation', 'J+1'],
  },
  {
    id: 'priorisation-rangement',
    label: 'Priorisation du rangement',
    description: 'Prioriser les tâches de rangement',
    personas: ['Ordonnanceur Assemblage'],
    objectives: ['Arbitrer'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['priorisation', 'rangement'],
  },
  {
    id: 'suivi-of-lances-retard',
    label: 'Suivi des OF lancés et en retard',
    description: 'Suivre les ordres de fabrication lancés en retard',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur'],
    objectives: ['Corriger', 'Piloter'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'lancé', 'retard'],
  },
  {
    id: 'suivi-tickets-priorites',
    label: 'Suivi des tickets et priorités',
    description: 'Suivre les tickets et leur niveau de priorité',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur'],
    objectives: ['Piloter', 'Arbitrer'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['ticket', 'priorité'],
  },
  {
    id: 'analyse-charge-avenir',
    label: 'Analyse de la charge à venir',
    description: 'Analyser la charge de travail prévue',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur', 'Master Planner'],
    objectives: ['Anticiper', 'Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['charge', 'analyse', 'avenir'],
  },
  {
    id: 'of-non-lances-retard',
    label: 'OF non lancés en retard',
    description: 'Identifier les OF qui devraient être lancés mais sont en retard',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur', 'Master Planner'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'non lancé', 'retard'],
  },
  {
    id: 'lancement-partiel-of',
    label: 'Lancement partiel des OF',
    description: 'Gérer les lancements partiels d\'ordres de fabrication',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['lancement', 'partiel', 'OF'],
  },
  {
    id: 'of-a-solder',
    label: 'OF à solder',
    description: 'Identifier les OF à solder',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'solder'],
  },
  {
    id: 'impact-replanifications-futures',
    label: 'Impact des replanifications futures',
    description: 'Analyser l\'impact des replanifications prévues',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur', 'Master Planner'],
    objectives: ['Anticiper'],
    horizon: 'Projection',
    impactZones: ['Production'],
    frequency: 'Weekly',
    pelicoViews: ['Production Control', 'Event Explorer'],
    keywords: ['impact', 'replanification', 'futur'],
  },
  {
    id: 'of-lances-composants-manquants',
    label: 'OF lancés avec composants manquants',
    description: 'Identifier les OF lancés mais avec des composants manquants',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur', 'Master Planner'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'composant', 'manquant'],
  },
  {
    id: 'anticipation-charge-manquants-critiques',
    label: 'Anticipation charge et manquants critiques',
    description: 'Anticiper la charge et identifier les manquants critiques',
    personas: ['Ordonnanceur Assemblage'],
    objectives: ['Anticiper'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['anticipation', 'charge', 'manquant', 'critique'],
  },
  {
    id: 'of-non-mouvementes',
    label: 'OF non mouvementés',
    description: 'Identifier les OF qui n\'ont pas été mouvementés',
    personas: ['Ordonnanceur Assemblage', 'Ordonnanceur', 'Master Planner'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'mouvementé'],
  },

  // === ORDONNANCEUR ===
  {
    id: 'lissage-charge-perimetre',
    label: 'Lissage de charge du périmètre',
    description: 'Lisser la charge de travail sur le périmètre',
    personas: ['Ordonnanceur'],
    objectives: ['Piloter', 'Arbitrer'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Weekly',
    pelicoViews: ['Production Control', 'Event Explorer', 'Simulation'],
    keywords: ['lissage', 'charge', 'périmètre'],
  },

  // === MASTER PLANNER ===
  {
    id: 'gestion-deviations-pdp-shipping',
    label: 'Gestion des déviations PDP Shipping',
    description: 'Gérer les déviations du plan directeur de production shipping',
    personas: ['Master Planner'],
    objectives: ['Corriger', 'Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['déviation', 'PDP', 'shipping'],
  },
  {
    id: 'opportunites-partielles-portefeuille-client',
    label: 'Opportunités partielles sur portefeuille client',
    description: 'Identifier les opportunités de livraison partielle',
    personas: ['Master Planner', 'Support Logistique'],
    objectives: ['Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['opportunité', 'partiel', 'client'],
  },
  {
    id: 'commandes-client-risque',
    label: 'Commandes client à risque',
    description: 'Identifier les commandes clients à risque de non-respect',
    personas: ['Master Planner', 'Support Logistique'],
    objectives: ['Anticiper'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['commande', 'client', 'risque'],
  },
  {
    id: 'pilotage-commandes-livraison',
    label: 'Pilotage des commandes en livraison',
    description: 'Piloter les commandes en cours de livraison',
    personas: ['Master Planner', 'Support Logistique'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['pilotage', 'commande', 'livraison'],
  },
  {
    id: 'suivi-objectifs-pdp-shipping',
    label: 'Suivi des objectifs PDP Shipping',
    description: 'Suivre le respect des objectifs du plan directeur',
    personas: ['Master Planner', 'Responsable Supply Chain'],
    objectives: ['Piloter', 'Reporter'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Weekly',
    pelicoViews: ['Customer Support', 'Value Engineering'],
    keywords: ['objectif', 'PDP', 'shipping'],
  },
  {
    id: 'commandes-client-pdp-shipping',
    label: 'Commandes client PDP Shipping',
    description: 'Suivre les commandes clients selon le PDP Shipping',
    personas: ['Master Planner'],
    objectives: ['Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['commande', 'client', 'PDP'],
  },
  {
    id: 'priorisation-actions-impact-portefeuille',
    label: 'Priorisation des actions à impact portefeuille',
    description: 'Prioriser les actions ayant un impact sur le portefeuille',
    personas: ['Master Planner', 'Support Logistique'],
    objectives: ['Arbitrer'],
    horizon: 'ThisWeek',
    impactZones: ['Customer', 'Business'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['priorisation', 'action', 'portefeuille'],
  },
  {
    id: 'priorisation-of-lancer',
    label: 'Priorisation des OF à lancer',
    description: 'Prioriser les ordres de fabrication à lancer',
    personas: ['Master Planner'],
    objectives: ['Arbitrer'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['priorisation', 'OF', 'lancer'],
  },
  {
    id: 'mise-jour-pdp-shipping-pl',
    label: 'Mise à jour PDP Shipping (PL)',
    description: 'Mettre à jour le plan directeur de production shipping',
    personas: ['Master Planner'],
    objectives: ['Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Weekly',
    pelicoViews: ['Customer Support'],
    keywords: ['mise à jour', 'PDP', 'PL'],
  },

  // === SUPPORT LOGISTIQUE ===
  {
    id: 'suivi-retards-client',
    label: 'Suivi des retards client',
    description: 'Suivre les retards de livraison aux clients',
    personas: ['Support Logistique'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['retard', 'client'],
  },
  {
    id: 'opportunites-partielles-retards',
    label: 'Opportunités partielles sur retards',
    description: 'Identifier les opportunités de livraison partielle sur retards',
    personas: ['Support Logistique'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['opportunité', 'partiel', 'retard'],
  },
  {
    id: 'anticipation-backlog-client-j7',
    label: 'Anticipation du backlog client J+7 (clients stratégiques)',
    description: 'Anticiper le backlog client à 7 jours pour les clients stratégiques',
    personas: ['Support Logistique'],
    objectives: ['Anticiper'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['anticipation', 'backlog', 'client', 'J+7'],
  },
  {
    id: 'gestion-commandes-bloquees-admin',
    label: 'Gestion des commandes bloquées administrativement',
    description: 'Gérer les commandes bloquées pour des raisons administratives',
    personas: ['Support Logistique'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['commande', 'bloquée', 'administratif'],
  },
  {
    id: 'opportunites-partielles-portefeuille-client',
    label: 'Opportunités partielles du portefeuille client',
    description: 'Identifier les opportunités de livraison partielle sur le portefeuille',
    personas: ['Support Logistique'],
    objectives: ['Piloter'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['opportunité', 'partiel', 'portefeuille'],
  },
  {
    id: 'pilotage-actions-en-cours',
    label: 'Pilotage des actions en cours',
    description: 'Piloter les actions en cours de traitement',
    personas: ['Support Logistique'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['pilotage', 'action'],
  },
  {
    id: 'suivi-respect-new-dar',
    label: 'Suivi du respect des New DAR',
    description: 'Suivre le respect des nouvelles dates d\'arrivée demandées',
    personas: ['Support Logistique'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['DAR', 'date', 'arrivée'],
  },
  {
    id: 'analyse-demandes-avance',
    label: 'Analyse des demandes d\'avance',
    description: 'Analyser les demandes d\'avance de livraison',
    personas: ['Support Logistique'],
    objectives: ['Arbitrer'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support', 'Production Control'],
    keywords: ['demande', 'avance'],
  },
  {
    id: 'anticipation-demandes-clients-changements-supply',
    label: 'Anticipation des demandes clients via changements Supply',
    description: 'Anticiper les demandes clients grâce aux changements Supply',
    personas: ['Support Logistique'],
    objectives: ['Anticiper'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['anticipation', 'demande', 'client', 'supply'],
  },
  {
    id: 'commandes-sans-evenements-amont',
    label: 'Commandes sans événements amont',
    description: 'Identifier les commandes sans événements amont',
    personas: ['Support Logistique'],
    objectives: ['Corriger'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['commande', 'événement', 'amont'],
  },
  {
    id: 'pilotage-commandes-escaladees-bloquees',
    label: 'Pilotage des commandes escaladées et bloquées',
    description: 'Piloter les commandes escaladées et bloquées',
    personas: ['Support Logistique'],
    objectives: ['Piloter', 'Arbitrer'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['pilotage', 'commande', 'escalade', 'bloquée'],
  },
  {
    id: 'mise-jour-new-dar-t-pl',
    label: 'Mise à jour du New DAR-T (commandes PL)',
    description: 'Mettre à jour les nouvelles dates d\'arrivée demandées',
    personas: ['Support Logistique'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['DAR', 'mise à jour', 'PL'],
  },

  // === RECETTE ===
  {
    id: 'of-attente-recette',
    label: 'OF en attente de recette',
    description: 'Suivre les ordres de fabrication en attente de recette',
    personas: ['Recette'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['OF', 'recette', 'attente'],
  },
  {
    id: 'pilotage-of-en-cours',
    label: 'Pilotage des OF en cours',
    description: 'Piloter les ordres de fabrication en cours',
    personas: ['Recette'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control', 'Escalation Room'],
    keywords: ['pilotage', 'OF', 'en cours'],
  },
  {
    id: 'points-arret-venir-of',
    label: 'Points d\'arrêt à venir sur OF',
    description: 'Identifier les points d\'arrêt à venir sur les OF',
    personas: ['Recette'],
    objectives: ['Anticiper'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['point', 'arrêt', 'OF'],
  },

  // === RESPONSABLE SUPPLY CHAIN ===
  {
    id: 'projection-chiffre-affaires',
    label: 'Projection du chiffre d\'affaires',
    description: 'Projeter le chiffre d\'affaires à venir',
    personas: ['Responsable Supply Chain'],
    objectives: ['Reporter'],
    horizon: 'Projection',
    impactZones: ['Business'],
    frequency: 'Monthly',
    pelicoViews: ['Value Engineering'],
    keywords: ['projection', 'CA', 'chiffre', 'affaires'],
  },

  // === DIRECTEUR SUPPLY CHAIN ===
  // (routines already covered above)

  // === RESPONSABLE ORDO & SUPPORT LOG ===
  {
    id: 'pilotage-activite-ordonnanceur',
    label: 'Pilotage de l\'activité ordonnanceur',
    description: 'Piloter l\'activité globale des ordonnanceurs',
    personas: ['Responsable Ordo & Support log'],
    objectives: ['Piloter', 'Reporter'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering', 'Production Control'],
    keywords: ['pilotage', 'activité', 'ordonnanceur'],
  },
  {
    id: 'animation-tickets-activite',
    label: 'Animation des tickets d\'activité',
    description: 'Animer et suivre les tickets d\'activité',
    personas: ['Responsable Ordo & Support log'],
    objectives: ['Piloter'],
    horizon: 'Today',
    impactZones: ['Production', 'Customer'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['animation', 'ticket', 'activité'],
  },
];

/**
 * Default routine sets per persona
 * These are preselected when a user selects a role
 */
export const PERSONA_DEFAULT_SETS: PersonaDefaultSets = {
  'Approvisionneur': [
    'commandes-sans-ar',
    'commandes-en-retard',
    'impact-des-retards',
    'actions-fournisseurs',
    'relances-fournisseurs',
    'solde-a-moins',
    'planning-fournisseur',
    'risques-rupture-fournisseur',
    'of-lancables',
    'priorisation-tickets',
    'suivi-priorites',
    'actions-en-cours',
  ],
  'Acheteur': [
    'suivi-evolution-actions-priorite',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
  ],
  'Manager Appro': [
    'top-fournisseurs-impact-business',
    'top-fournisseurs-retard',
    'top-fournisseurs-sans-ar',
    'repartition-actions-equipes',
    'suivi-priorites',
    'nettoyage-tickets',
    'suivi-kpis-pilotage',
  ],
  'Ordonnanceur Assemblage': [
    'preparation-montage-j1',
    'priorisation-rangement',
    'suivi-of-lances-retard',
    'suivi-tickets-priorites',
    'analyse-charge-avenir',
    'of-non-lances-retard',
    'lancement-partiel-of',
    'of-a-solder',
    'impact-replanifications-futures',
    'of-lances-composants-manquants',
    'anticipation-charge-manquants-critiques',
    'of-non-mouvementes',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
  ],
  'Ordonnanceur': [
    'preparation-montage-j1',
    'suivi-of-lances-retard',
    'suivi-tickets-priorites',
    'analyse-charge-avenir',
    'of-non-lances-retard',
    'lancement-partiel-of',
    'of-a-solder',
    'impact-replanifications-futures',
    'of-lances-composants-manquants',
    'of-non-mouvementes',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
    'lissage-charge-perimetre',
  ],
  'Master Planner': [
    'analyse-charge-avenir',
    'of-non-lances-retard',
    'gestion-deviations-pdp-shipping',
    'opportunites-partielles-portefeuille-client',
    'commandes-client-risque',
    'pilotage-commandes-livraison',
    'impact-replanifications-futures',
    'of-lances-composants-manquants',
    'of-non-mouvementes',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
    'suivi-objectifs-pdp-shipping',
    'commandes-client-pdp-shipping',
    'priorisation-actions-impact-portefeuille',
    'priorisation-of-lancer',
    'suivi-kpis-pilotage',
    'mise-jour-pdp-shipping-pl',
  ],
  'Support Logistique': [
    'suivi-retards-client',
    'opportunites-partielles-retards',
    'anticipation-backlog-client-j7',
    'gestion-commandes-bloquees-admin',
    'opportunites-partielles-portefeuille-client',
    'commandes-client-risque',
    'pilotage-actions-en-cours',
    'pilotage-commandes-livraison',
    'suivi-respect-new-dar',
    'analyse-demandes-avance',
    'anticipation-demandes-clients-changements-supply',
    'commandes-sans-evenements-amont',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
    'priorisation-actions-impact-portefeuille',
    'pilotage-commandes-escaladees-bloquees',
    'mise-jour-new-dar-t-pl',
  ],
  'Recette': [
    'of-attente-recette',
    'pilotage-of-en-cours',
    'points-arret-venir-of',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
  ],
  'Responsable Supply Chain': [
    'projection-chiffre-affaires',
    'suivi-priorites',
    'nettoyage-tickets',
    'suivi-objectifs-pdp-shipping',
    'suivi-kpis-pilotage',
  ],
  'Directeur Supply Chain': [
    'top-fournisseurs-impact-business',
    'top-fournisseurs-retard',
    'top-fournisseurs-sans-ar',
    'repartition-actions-equipes',
    'suivi-priorites',
    'nettoyage-tickets',
    'suivi-kpis-pilotage',
  ],
  'Responsable Ordo & Support log': [
    'pilotage-activite-ordonnanceur',
    'animation-tickets-activite',
  ],
  'Autre / Mixte': [],
};

/**
 * Get routine by ID
 */
export function getRoutineById(id: string): RoutineLibraryEntry | undefined {
  return ROUTINE_LIBRARY.find((r) => r.id === id);
}

/**
 * Get all routines for a persona
 */
export function getRoutinesByPersona(persona: Persona): RoutineLibraryEntry[] {
  return ROUTINE_LIBRARY.filter((r) => r.personas.includes(persona));
}

/**
 * Get default routines for a persona
 */
export function getDefaultRoutinesForPersona(persona: Persona): RoutineLibraryEntry[] {
  const defaultIds = PERSONA_DEFAULT_SETS[persona] || [];
  return defaultIds
    .map((id) => getRoutineById(id))
    .filter((r): r is RoutineLibraryEntry => r !== undefined);
}

