/**
 * Onboarding Routine Library
 * 
 * Normalized routine library with tags for multiple discovery paths.
 * Each routine can belong to multiple personas and have multiple objectives.
 * 
 * Naming convention for IDs: kebab-case, descriptive (e.g., 'commandes-sans-ar')
 * 
 * IMPORTANT: Routines with identical labels across personas share the same ID
 * (e.g., "Suivi des priorités" appears for multiple personas but has one ID)
 */

import type {
  RoutineLibraryEntry,
  PersonaDefaultSets,
  Persona,
} from './types';

export const ROUTINE_LIBRARY: RoutineLibraryEntry[] = [
  // === SUPPLY PLANNER ===
  {
    id: 'commandes-sans-ar',
    label: 'Orders without AR',
    description: 'Track purchase orders pending acknowledgment receipt',
    personas: ['Supply Planner'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['AR', 'acknowledgment', 'receipt', 'purchase order'],
    primaryPelicoView: 'Supply',
    requiredColumns: ['arStatus'],
    filters: [
      {
        columnId: 'arStatus',
        filterId: 'ar-status',
        condition: 'is',
        values: ['No AR'],
      },
      {
        columnId: 'createdDate',
        filterId: 'date-comparison',
        condition: 'lessThan',
        dateExpression: '1 week ago',
        values: [],
      },
    ],
  },
  {
    id: 'commandes-en-retard',
    label: 'Delayed orders',
    description: 'Identify and manage delayed supplier orders',
    personas: ['Supply Planner'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['delay', 'late', 'supplier', 'order'],
  },
  {
    id: 'impact-des-retards',
    label: 'Delay impact analysis',
    description: 'Analyze the impact of supplier delays on production',
    personas: ['Supply Planner'],
    objectives: ['Anticipate', 'Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier', 'Production'],
    frequency: 'Daily',
    pelicoViews: ['Supply', 'Event Explorer'],
    keywords: ['impact', 'delay', 'production', 'supplier'],
  },
  {
    id: 'actions-fournisseurs',
    label: 'Supplier actions',
    description: 'Track ongoing actions with suppliers',
    personas: ['Supply Planner'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['action', 'supplier', 'follow-up'],
  },
  {
    id: 'relances-fournisseurs',
    label: 'Supplier follow-ups',
    description: 'Manage necessary follow-ups with suppliers',
    personas: ['Supply Planner'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['follow-up', 'supplier', 'reminder'],
  },
  {
    id: 'solde-a-moins',
    label: 'Negative balances',
    description: 'Track negative balances and urgent requirements',
    personas: ['Supply Planner'],
    objectives: ['Anticipate'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['balance', 'negative', 'stock', 'inventory'],
  },
  {
    id: 'reporting-management',
    label: 'Management reporting',
    description: 'Generate tracking reports for management',
    personas: ['Supply Planner'],
    objectives: ['Report'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Escalation Room'],
    keywords: ['reporting', 'management', 'dashboard', 'KPI'],
  },
  {
    id: 'planning-fournisseur',
    label: 'Supplier delivery schedule',
    description: 'Track supplier delivery schedules',
    personas: ['Supply Planner'],
    objectives: ['Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['planning', 'schedule', 'delivery', 'supplier'],
  },
  {
    id: 'impact-fournisseur',
    label: 'Supplier impact analysis',
    description: 'Analyze overall supplier impact',
    personas: ['Supply Planner'],
    objectives: ['Monitor', 'Report'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Weekly',
    pelicoViews: ['Supply'],
    keywords: ['impact', 'supplier', 'performance'],
  },
  {
    id: 'collaboration-fournisseur',
    label: 'Supplier collaboration',
    description: 'Facilitate collaboration with suppliers',
    personas: ['Supply Planner'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Supply'],
    keywords: ['collaboration', 'supplier', 'partnership'],
  },
  {
    id: 'risques-rupture-fournisseur',
    label: 'Supplier stockout risks',
    description: 'Anticipate stockout risks at suppliers',
    personas: ['Supply Planner'],
    objectives: ['Anticipate'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['risk', 'stockout', 'shortage', 'supplier'],
  },
  {
    id: 'of-lancables',
    label: 'Releasable work orders',
    description: 'Identify work orders ready to be released',
    personas: ['Supply Planner'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'WO', 'release', 'production'],
  },
  {
    id: 'of-sous-traitance-non-servis',
    label: 'Unfulfilled subcontract work orders',
    description: 'Track unfulfilled subcontract work orders',
    personas: ['Supply Planner'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'subcontract', 'outsourcing'],
  },
  {
    id: 'priorisation-tickets',
    label: 'Ticket prioritization',
    description: 'Prioritize tickets based on urgency and impact',
    personas: ['Supply Planner'],
    objectives: ['Prioritize'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['prioritization', 'ticket', 'priority', 'escalation'],
  },
  {
    id: 'suivi-priorites',
    label: 'Priority tracking',
    description: 'Track priority evolution and resolution',
    personas: [
      'Supply Planner',
      'Buyer',
      'Procurement Manager',
      'Assembly Scheduler',
      'Scheduler',
      'Master Planner',
      'Logistics Support',
      'Quality Control',
      'Supply Chain Manager',
      'Supply Chain Director',
    ],
    objectives: ['Monitor', 'Prioritize'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer', 'Business'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['priority', 'tracking', 'monitoring'],
  },
  {
    id: 'actions-en-cours',
    label: 'Ongoing actions',
    description: 'Track progress of ongoing actions',
    personas: [
      'Supply Planner',
      'Buyer',
      'Procurement Manager',
      'Assembly Scheduler',
      'Scheduler',
      'Master Planner',
      'Logistics Support',
      'Quality Control',
      'Supply Chain Manager',
    ],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['action', 'ongoing', 'tracking'],
  },
  {
    id: 'nettoyage-tickets',
    label: 'Ticket cleanup',
    description: 'Clean up and close obsolete tickets',
    personas: [
      'Supply Planner',
      'Buyer',
      'Procurement Manager',
      'Assembly Scheduler',
      'Scheduler',
      'Master Planner',
      'Logistics Support',
      'Quality Control',
      'Supply Chain Manager',
      'Supply Chain Director',
    ],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Supplier', 'Production', 'Customer'],
    frequency: 'Weekly',
    pelicoViews: ['Escalation Room'],
    keywords: ['cleanup', 'ticket', 'closure'],
  },

  // === BUYER ===
  {
    id: 'suivi-evolution-actions-priorite',
    label: 'Priority-based action tracking',
    description: 'Track evolution of actions classified by priority',
    personas: ['Buyer'],
    objectives: ['Monitor', 'Prioritize'],
    horizon: 'Today',
    impactZones: ['Supplier'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['evolution', 'action', 'priority'],
  },

  // === PROCUREMENT MANAGER ===
  {
    id: 'top-fournisseurs-impact-business',
    label: 'Top suppliers by business impact',
    description: 'Identify suppliers with the highest business impact',
    personas: ['Procurement Manager', 'Supply Chain Director'],
    objectives: ['Report', 'Prioritize'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering'],
    keywords: ['top', 'supplier', 'impact', 'business'],
  },
  {
    id: 'top-fournisseurs-retard',
    label: 'Top delayed suppliers',
    description: 'Identify suppliers with the most delays',
    personas: ['Procurement Manager', 'Supply Chain Director'],
    objectives: ['Correct', 'Report'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering'],
    keywords: ['top', 'supplier', 'delay'],
  },
  {
    id: 'top-fournisseurs-sans-ar',
    label: 'Top suppliers without AR',
    description: 'Identify suppliers with the most orders without AR',
    personas: ['Procurement Manager', 'Supply Chain Director'],
    objectives: ['Monitor', 'Report'],
    horizon: 'ThisWeek',
    impactZones: ['Supplier'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering'],
    keywords: ['top', 'supplier', 'AR', 'acknowledgment'],
  },
  {
    id: 'repartition-actions-equipes',
    label: 'Team action distribution',
    description: 'Visualize action distribution across teams',
    personas: ['Procurement Manager', 'Supply Chain Director'],
    objectives: ['Report', 'Prioritize'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Escalation Room'],
    keywords: ['distribution', 'action', 'team'],
  },
  {
    id: 'suivi-kpis-pilotage',
    label: 'Management KPI tracking',
    description: 'Track key performance indicators',
    personas: ['Procurement Manager', 'Master Planner', 'Supply Chain Manager', 'Supply Chain Director'],
    objectives: ['Report', 'Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Business'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering', 'Production Control', 'Customer Support'],
    keywords: ['KPI', 'indicator', 'management'],
  },

  // === ASSEMBLY SCHEDULER ===
  {
    id: 'preparation-montage-j1',
    label: 'Assembly preparation for D+1',
    description: 'Prepare assembly setup for tomorrow',
    personas: ['Assembly Scheduler', 'Scheduler'],
    objectives: ['Anticipate', 'Monitor'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['assembly', 'preparation', 'D+1'],
  },
  {
    id: 'priorisation-rangement',
    label: 'Storage prioritization',
    description: 'Prioritize storage tasks',
    personas: ['Assembly Scheduler'],
    objectives: ['Prioritize'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['prioritization', 'storage'],
  },
  {
    id: 'suivi-of-lances-retard',
    label: 'Tracking of released and delayed work orders',
    description: 'Track work orders released but delayed',
    personas: ['Assembly Scheduler', 'Scheduler'],
    objectives: ['Correct', 'Monitor'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'released', 'delay'],
  },
  {
    id: 'suivi-tickets-priorites',
    label: 'Ticket and priority tracking',
    description: 'Track tickets and their priority level',
    personas: ['Assembly Scheduler', 'Scheduler'],
    objectives: ['Monitor', 'Prioritize'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['ticket', 'priority'],
  },
  {
    id: 'analyse-charge-avenir',
    label: 'Upcoming workload analysis',
    description: 'Analyze planned workload',
    personas: ['Assembly Scheduler', 'Scheduler', 'Master Planner'],
    objectives: ['Anticipate', 'Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['workload', 'analysis', 'upcoming'],
  },
  {
    id: 'of-non-lances-retard',
    label: 'Delayed unreleased work orders',
    description: 'Identify work orders that should be released but are delayed',
    personas: ['Assembly Scheduler', 'Scheduler', 'Master Planner'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'unreleased', 'delay'],
  },
  {
    id: 'lancement-partiel-of',
    label: 'Partial work order release',
    description: 'Manage partial work order releases',
    personas: ['Assembly Scheduler', 'Scheduler'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['release', 'partial', 'work order'],
  },
  {
    id: 'of-a-solder',
    label: 'Work orders to close',
    description: 'Identify work orders to close',
    personas: ['Assembly Scheduler', 'Scheduler'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'close'],
  },
  {
    id: 'impact-replanifications-futures',
    label: 'Impact of future rescheduling',
    description: 'Analyze impact of planned rescheduling',
    personas: ['Assembly Scheduler', 'Scheduler', 'Master Planner'],
    objectives: ['Anticipate'],
    horizon: 'Projection',
    impactZones: ['Production'],
    frequency: 'Weekly',
    pelicoViews: ['Production Control', 'Event Explorer'],
    keywords: ['impact', 'rescheduling', 'future'],
  },
  {
    id: 'of-lances-composants-manquants',
    label: 'Released work orders with missing components',
    description: 'Identify released work orders with missing components',
    personas: ['Assembly Scheduler', 'Scheduler', 'Master Planner'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'component', 'missing'],
  },
  {
    id: 'anticipation-charge-manquants-critiques',
    label: 'Critical workload and shortages anticipation',
    description: 'Anticipate workload and identify critical shortages',
    personas: ['Assembly Scheduler'],
    objectives: ['Anticipate'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['anticipation', 'workload', 'shortage', 'critical'],
  },
  {
    id: 'of-non-mouvementes',
    label: 'Unmoved work orders',
    description: 'Identify work orders that have not been moved',
    personas: ['Assembly Scheduler', 'Scheduler', 'Master Planner'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'moved'],
  },

  // === SCHEDULER ===
  {
    id: 'lissage-charge-perimetre',
    label: 'Perimeter workload smoothing',
    description: 'Smooth workload across the perimeter',
    personas: ['Scheduler'],
    objectives: ['Monitor', 'Prioritize'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Weekly',
    pelicoViews: ['Production Control', 'Event Explorer', 'Simulation'],
    keywords: ['smoothing', 'workload', 'perimeter'],
  },

  // === MASTER PLANNER ===
  {
    id: 'gestion-deviations-pdp-shipping',
    label: 'PDP Shipping deviation management',
    description: 'Manage master production plan shipping deviations',
    personas: ['Master Planner'],
    objectives: ['Correct', 'Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['deviation', 'MPS', 'shipping'],
  },
  {
    id: 'opportunites-partielles-portefeuille-client',
    label: 'Partial delivery opportunities on customer portfolio',
    description: 'Identify partial delivery opportunities',
    personas: ['Master Planner', 'Logistics Support'],
    objectives: ['Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['opportunity', 'partial', 'customer'],
  },
  {
    id: 'commandes-client-risque',
    label: 'At-risk customer orders',
    description: 'Identify customer orders at risk of non-compliance',
    personas: ['Master Planner', 'Logistics Support'],
    objectives: ['Anticipate'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['order', 'customer', 'risk'],
  },
  {
    id: 'pilotage-commandes-livraison',
    label: 'In-transit order management',
    description: 'Manage orders in transit',
    personas: ['Master Planner', 'Logistics Support'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['management', 'order', 'delivery'],
  },
  {
    id: 'suivi-objectifs-pdp-shipping',
    label: 'PDP Shipping objectives tracking',
    description: 'Track compliance with master plan objectives',
    personas: ['Master Planner', 'Supply Chain Manager'],
    objectives: ['Monitor', 'Report'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Weekly',
    pelicoViews: ['Customer Support', 'Value Engineering'],
    keywords: ['objective', 'MPS', 'shipping'],
  },
  {
    id: 'commandes-client-pdp-shipping',
    label: 'Customer orders PDP Shipping',
    description: 'Track customer orders according to PDP Shipping',
    personas: ['Master Planner'],
    objectives: ['Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['order', 'customer', 'MPS'],
  },
  {
    id: 'priorisation-actions-impact-portefeuille',
    label: 'Portfolio impact action prioritization',
    description: 'Prioritize actions impacting the portfolio',
    personas: ['Master Planner', 'Logistics Support'],
    objectives: ['Prioritize'],
    horizon: 'ThisWeek',
    impactZones: ['Customer', 'Business'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room', 'Value Engineering'],
    keywords: ['prioritization', 'action', 'portfolio'],
  },
  {
    id: 'priorisation-of-lancer',
    label: 'Work order release prioritization',
    description: 'Prioritize work orders to release',
    personas: ['Master Planner'],
    objectives: ['Prioritize'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['prioritization', 'work order', 'release'],
  },
  {
    id: 'mise-jour-pdp-shipping-pl',
    label: 'PDP Shipping update (PL)',
    description: 'Update master production plan shipping',
    personas: ['Master Planner'],
    objectives: ['Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Weekly',
    pelicoViews: ['Customer Support'],
    keywords: ['update', 'MPS', 'PL'],
  },

  // === SUPPORT LOGISTIQUE ===
  {
    id: 'suivi-retards-client',
    label: 'Customer delay tracking',
    description: 'Track delivery delays to customers',
    personas: ['Logistics Support'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['delay', 'customer'],
  },
  {
    id: 'opportunites-partielles-retards',
    label: 'Partial opportunities on delays',
    description: 'Identify partial delivery opportunities on delays',
    personas: ['Logistics Support'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['opportunity', 'partial', 'delay'],
  },
  {
    id: 'anticipation-backlog-client-j7',
    label: 'Customer backlog anticipation D+7 (strategic customers)',
    description: 'Anticipate customer backlog 7 days ahead for strategic customers',
    personas: ['Logistics Support'],
    objectives: ['Anticipate'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['anticipation', 'backlog', 'customer', 'D+7'],
  },
  {
    id: 'gestion-commandes-bloquees-admin',
    label: 'Administratively blocked order management',
    description: 'Manage orders blocked for administrative reasons',
    personas: ['Logistics Support'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['order', 'blocked', 'administrative'],
  },
  {
    id: 'opportunites-partielles-portefeuille-client',
    label: 'Customer portfolio partial opportunities',
    description: 'Identify partial delivery opportunities on the portfolio',
    personas: ['Logistics Support'],
    objectives: ['Monitor'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['opportunity', 'partial', 'portfolio'],
  },
  {
    id: 'pilotage-actions-en-cours',
    label: 'Ongoing action management',
    description: 'Manage actions currently being processed',
    personas: ['Logistics Support'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['management', 'action'],
  },
  {
    id: 'suivi-respect-new-dar',
    label: 'New DAR compliance tracking',
    description: 'Track compliance with requested new arrival dates',
    personas: ['Logistics Support'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['RAD', 'date', 'arrival'],
  },
  {
    id: 'analyse-demandes-avance',
    label: 'Advance request analysis',
    description: 'Analyze advance delivery requests',
    personas: ['Logistics Support'],
    objectives: ['Prioritize'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support', 'Production Control'],
    keywords: ['request', 'advance'],
  },
  {
    id: 'anticipation-demandes-clients-changements-supply',
    label: 'Customer demand anticipation via Supply changes',
    description: 'Anticipate customer demands through Supply changes',
    personas: ['Logistics Support'],
    objectives: ['Anticipate'],
    horizon: 'ThisWeek',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['anticipation', 'demand', 'customer', 'supply'],
  },
  {
    id: 'commandes-sans-evenements-amont',
    label: 'Orders without upstream events',
    description: 'Identify orders without upstream events',
    personas: ['Logistics Support'],
    objectives: ['Correct'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['order', 'event', 'upstream'],
  },
  {
    id: 'pilotage-commandes-escaladees-bloquees',
    label: 'Escalated and blocked order management',
    description: 'Manage escalated and blocked orders',
    personas: ['Logistics Support'],
    objectives: ['Monitor', 'Prioritize'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['management', 'order', 'escalation', 'blocked'],
  },
  {
    id: 'mise-jour-new-dar-t-pl',
    label: 'New DAR-T update (PL orders)',
    description: 'Update requested new arrival dates',
    personas: ['Logistics Support'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Customer'],
    frequency: 'Daily',
    pelicoViews: ['Customer Support'],
    keywords: ['RAD', 'update', 'PL'],
  },

  // === RECETTE ===
  {
    id: 'of-attente-recette',
    label: 'Work orders pending quality control',
    description: 'Track work orders pending quality control',
    personas: ['Quality Control'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['work order', 'quality control', 'pending'],
  },
  {
    id: 'pilotage-of-en-cours',
    label: 'Ongoing work order management',
    description: 'Manage ongoing work orders',
    personas: ['Quality Control'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control', 'Escalation Room'],
    keywords: ['management', 'work order', 'ongoing'],
  },
  {
    id: 'points-arret-venir-of',
    label: 'Upcoming hold points on work orders',
    description: 'Identify upcoming hold points on work orders',
    personas: ['Quality Control'],
    objectives: ['Anticipate'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Daily',
    pelicoViews: ['Production Control'],
    keywords: ['point', 'hold', 'work order'],
  },

  // === RESPONSABLE SUPPLY CHAIN ===
  {
    id: 'projection-chiffre-affaires',
    label: 'Revenue projection',
    description: 'Project upcoming revenue',
    personas: ['Supply Chain Manager'],
    objectives: ['Report'],
    horizon: 'Projection',
    impactZones: ['Business'],
    frequency: 'Monthly',
    pelicoViews: ['Value Engineering'],
    keywords: ['projection', 'revenue', 'business'],
  },

  // === DIRECTEUR SUPPLY CHAIN ===
  // (routines already covered above)

  // === RESPONSABLE ORDO & SUPPORT LOG ===
  {
    id: 'pilotage-activite-ordonnanceur',
    label: 'Scheduler activity management',
    description: 'Manage overall scheduler activity',
    personas: ['Scheduling & Logistics Manager'],
    objectives: ['Monitor', 'Report'],
    horizon: 'ThisWeek',
    impactZones: ['Production'],
    frequency: 'Weekly',
    pelicoViews: ['Value Engineering', 'Production Control'],
    keywords: ['management', 'activity', 'scheduler'],
  },
  {
    id: 'animation-tickets-activite',
    label: 'Activity ticket management',
    description: 'Manage and track activity tickets',
    personas: ['Scheduling & Logistics Manager'],
    objectives: ['Monitor'],
    horizon: 'Today',
    impactZones: ['Production', 'Customer'],
    frequency: 'Daily',
    pelicoViews: ['Escalation Room'],
    keywords: ['management', 'ticket', 'activity'],
  },
];

/**
 * Default routine sets per persona
 * These are preselected when a user selects a role
 */
export const PERSONA_DEFAULT_SETS: PersonaDefaultSets = {
  'Supply Planner': [
    'commandes-sans-ar',
    'commandes-en-retard',
    'impact-des-retards',
    'actions-fournisseurs',
    'relances-fournisseurs',
    'solde-a-moins',
    'planning-fournisseur',
    'risques-rupture-fournisseur',
    'of-lancables',
    'priorisation-tickets',
    'suivi-priorites',
    'actions-en-cours',
  ],
  'Buyer': [
    'suivi-evolution-actions-priorite',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
  ],
  'Procurement Manager': [
    'top-fournisseurs-impact-business',
    'top-fournisseurs-retard',
    'top-fournisseurs-sans-ar',
    'repartition-actions-equipes',
    'suivi-priorites',
    'nettoyage-tickets',
    'suivi-kpis-pilotage',
  ],
  'Assembly Scheduler': [
    'preparation-montage-j1',
    'priorisation-rangement',
    'suivi-of-lances-retard',
    'suivi-tickets-priorites',
    'analyse-charge-avenir',
    'of-non-lances-retard',
    'lancement-partiel-of',
    'of-a-solder',
    'impact-replanifications-futures',
    'of-lances-composants-manquants',
    'anticipation-charge-manquants-critiques',
    'of-non-mouvementes',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
  ],
  'Scheduler': [
    'preparation-montage-j1',
    'suivi-of-lances-retard',
    'suivi-tickets-priorites',
    'analyse-charge-avenir',
    'of-non-lances-retard',
    'lancement-partiel-of',
    'of-a-solder',
    'impact-replanifications-futures',
    'of-lances-composants-manquants',
    'of-non-mouvementes',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
    'lissage-charge-perimetre',
  ],
  'Master Planner': [
    'analyse-charge-avenir',
    'of-non-lances-retard',
    'gestion-deviations-pdp-shipping',
    'opportunites-partielles-portefeuille-client',
    'commandes-client-risque',
    'pilotage-commandes-livraison',
    'impact-replanifications-futures',
    'of-lances-composants-manquants',
    'of-non-mouvementes',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
    'suivi-objectifs-pdp-shipping',
    'commandes-client-pdp-shipping',
    'priorisation-actions-impact-portefeuille',
    'priorisation-of-lancer',
    'suivi-kpis-pilotage',
    'mise-jour-pdp-shipping-pl',
  ],
  'Logistics Support': [
    'suivi-retards-client',
    'opportunites-partielles-retards',
    'anticipation-backlog-client-j7',
    'gestion-commandes-bloquees-admin',
    'opportunites-partielles-portefeuille-client',
    'commandes-client-risque',
    'pilotage-actions-en-cours',
    'pilotage-commandes-livraison',
    'suivi-respect-new-dar',
    'analyse-demandes-avance',
    'anticipation-demandes-clients-changements-supply',
    'commandes-sans-evenements-amont',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
    'priorisation-actions-impact-portefeuille',
    'pilotage-commandes-escaladees-bloquees',
    'mise-jour-new-dar-t-pl',
  ],
  'Quality Control': [
    'of-attente-recette',
    'pilotage-of-en-cours',
    'points-arret-venir-of',
    'suivi-priorites',
    'actions-en-cours',
    'nettoyage-tickets',
  ],
  'Supply Chain Manager': [
    'projection-chiffre-affaires',
    'suivi-priorites',
    'nettoyage-tickets',
    'suivi-objectifs-pdp-shipping',
    'suivi-kpis-pilotage',
  ],
  'Supply Chain Director': [
    'top-fournisseurs-impact-business',
    'top-fournisseurs-retard',
    'top-fournisseurs-sans-ar',
    'repartition-actions-equipes',
    'suivi-priorites',
    'nettoyage-tickets',
    'suivi-kpis-pilotage',
  ],
  'Scheduling & Logistics Manager': [
    'pilotage-activite-ordonnanceur',
    'animation-tickets-activite',
  ],
  'Other / Mixed': [],
};

/**
 * Get routine by ID
 */
export function getRoutineById(id: string): RoutineLibraryEntry | undefined {
  return ROUTINE_LIBRARY.find((r) => r.id === id);
}

/**
 * Get all routines for a persona
 */
export function getRoutinesByPersona(persona: Persona): RoutineLibraryEntry[] {
  return ROUTINE_LIBRARY.filter((r) => r.personas.includes(persona));
}

/**
 * Get default routines for a persona
 */
export function getDefaultRoutinesForPersona(persona: Persona): RoutineLibraryEntry[] {
  const defaultIds = PERSONA_DEFAULT_SETS[persona] || [];
  return defaultIds
    .map((id) => getRoutineById(id))
    .filter((r): r is RoutineLibraryEntry => r !== undefined);
}

